version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chat-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  chat-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    # --- THAY THẾ HOÀN TOÀN BẰNG KHỐI NÀY ---
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=123456
      - DB_NAME=chatdb
      - REDIS_HOST=redis
      - JWT_SECRET=nekokiyoshi6922112005!@#$%^&*()_+
    # ------------------------------------
    restart: unless-stopped
  
  # Optional: NGINX for reverse proxy and TLS termination
  # nginx:
  #   image: nginx:latest
  #   container_name: chat-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/certs:/etc/letsencrypt
  #   depends_on:
  #     - chat-server
  #   restart: unless-stopped

volumes:
  postgres_data: